version: '3'
services:
  
  #Laravel Service
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_image
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel_app
      SERVICE_TAGS: dev
    working_dir: /var/www/laravel-src/
    volumes:
      - ./laravel-src/:/var/www/laravel-src/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network

  #Nginx Service
  nginx_webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel-src/:/var/www/laravel-src/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network

  #MySQL Service
  mysql_database:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql_database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      # - database_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql-logs/:/var/lib/mysql/
    networks:
      - laravel-network
    
  #Composer Service
  composer:
    image: composer:latest
    container_name: composer
    command: ["composer", "install"]
    volumes:
      - ./laravel-src/:/app

#Docker Networks
networks:
  laravel-network:
    driver: bridge

#Docker Volumes
# volumes:
#   database_data:
#     driver: local